In [1]:
import numpy as np
import torch

In [2]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [3]:
x[1,1]

tensor(3)

In [6]:
x[:,1]

tensor([1, 3, 5])

In [7]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [8]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
z = x.view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
x[0] = 99
z

tensor([[99,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [14]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x.shape

torch.Size([10])

In [17]:
# Infer what the 2nd dimension
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
x.view(-1, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])
a+b

tensor([5., 7., 9.])

In [20]:
torch.add(a,b)

tensor([5., 7., 9.])

In [21]:
a.mul(b)

tensor([ 4., 10., 18.])

In [22]:
a*b

tensor([ 4., 10., 18.])

In [23]:
a.dot(b)

tensor(32.)

In [25]:
a = torch.tensor([[0,2,4],[1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [28]:
b = torch.tensor([[6,7],[8,9],[10,11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [29]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [30]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [31]:
x = torch.tensor([2.,3.,4.,5.])
x

tensor([2., 3., 4., 5.])

In [32]:
x.norm()

tensor(7.3485)

In [33]:
x.numel()

4

In [34]:
len(x)

4

In [35]:
a.numel()

6