In [1]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.4.1'

In [15]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [16]:
print(arr.dtype)
print(type(arr))

int64
<class 'numpy.ndarray'>


In [18]:
x = torch.from_numpy(arr)
(x)

tensor([1, 2, 3, 4, 5])

In [19]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [20]:
arr_2d = np.arange(0.0, 12.0)
arr_2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [21]:
arr_2d = arr_2d.reshape(4,3)
arr_2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [22]:
x2 = torch.from_numpy(arr_2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [25]:
print(x)
print(arr)

tensor([1, 2, 3, 4, 5])
[1 2 3 4 5]


In [26]:
arr[0] = 99
print(arr)
print(x)

[99  2  3  4  5]
tensor([99,  2,  3,  4,  5])


##### There is a direct link between the array and the tensors as we are using this (from_numpy(), as_tensor())function to create the tensors out of the array. So Basicallly it will convert the data to the tensor but it will work as shallow copy()

In [27]:
my_arr = np.arange(0, 10)
print(my_arr)
#Deep copy
my_tensor = torch.tensor(my_arr)
print(my_tensor)
#Shallow copy
other_tensor = torch.from_numpy(my_arr)
print(other_tensor)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [29]:
my_arr[0]=99
print(my_arr)
print(f"Deep Copy {my_tensor}")
print(f"shallow copy {other_tensor}")

[99  1  2  3  4  5  6  7  8  9]
Deep Copy tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
shallow copy tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])


In [30]:
new_arr = np.array([1,2,3,4,5])
new_arr.dtype

dtype('int64')

In [34]:
t = torch.tensor(new_arr)
t.dtype

torch.int64

In [37]:
floating = torch.Tensor(new_arr)
print(floating)
floating.dtype

tensor([1., 2., 3., 4., 5.])


torch.float32

In [39]:
my_tensor = torch.FloatTensor(new_arr)
my_tensor

tensor([1., 2., 3., 4., 5.])

In [41]:
torch.empty(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [42]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [44]:
torch.zeros(4,3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [45]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [47]:
torch.arange(0, 18, 2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [50]:
torch.linspace(0, 18, 12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [51]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [52]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [54]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [55]:
# Random sample form a uniform distribution over 0 & 1
torch.rand(4,3)

tensor([[0.1666, 0.8299, 0.1746],
        [0.5966, 0.7682, 0.6279],
        [0.5470, 0.4477, 0.8154],
        [0.9594, 0.0105, 0.2720]])

In [56]:
# Standard normal distrbution mean 0 standard deviation 1
torch.randn(4,3)

tensor([[ 0.5022,  0.0697,  2.5378],
        [-1.9644, -2.7767,  0.8634],
        [-0.3763, -0.7719, -0.0180],
        [ 0.1612,  0.2383,  0.3740]])

In [57]:
torch.randint(low=0, high=10, size=(5,5))

tensor([[3, 8, 8, 9, 2],
        [4, 1, 6, 7, 4],
        [1, 6, 3, 9, 8],
        [5, 6, 8, 3, 8],
        [3, 4, 4, 7, 5]])

In [58]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [59]:
x.shape

torch.Size([2, 5])

In [61]:
torch.rand_like(x)

tensor([[0.3281, 0.3692, 0.3520, 0.4539, 0.7696],
        [0.7124, 0.5515, 0.4916, 0.3567, 0.2654]])

In [62]:
torch.randn_like(x)

tensor([[ 0.6763,  0.3890,  0.6186,  0.0233,  0.1830],
        [-0.0368, -1.6932,  1.7719, -0.5778,  0.5518]])

In [63]:
torch.randint_like(x, low=0, high=11)

tensor([[ 0.,  3.,  5.,  8.,  6.],
        [10.,  9.,  3.,  1.,  1.]])

In [66]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])