In [1]:
import torch

In [2]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [3]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x +1
y

tensor(63., grad_fn=<AddBackward0>)

In [4]:
type(y)

torch.Tensor

In [5]:
y.backward()

In [6]:
# Get the gradient of y with respect to x, which is dy/dx = 8*x**3+3*x**2+6*x+5 = 93 (for x=2.0)
x.grad

tensor(93.)

In [20]:
x = torch.tensor([[1.,2.,3.],[3.,2.,1]], requires_grad=True)
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [21]:
y = 3*x + 2
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [22]:
z = 2*y**2
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [23]:
out = z.mean()
out

tensor(140., grad_fn=<MeanBackward0>)

In [24]:
out.backward()
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])