In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.rand(1)

array([0.34828306])

In [11]:
np.random.rand(25)

array([0.31796492, 0.5456187 , 0.54236129, 0.17435097, 0.57368293,
       0.74562704, 0.66354244, 0.49970732, 0.39701759, 0.54340126,
       0.03801924, 0.14698743, 0.38805226, 0.01914661, 0.17839386,
       0.34859253, 0.73160557, 0.23389093, 0.59428974, 0.92777297,
       0.96486222, 0.97436121, 0.30046614, 0.80235759, 0.54931997])

In [17]:
np.arange(1, 101)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [18]:
np.linspace(0,1.20)

array([0.        , 0.0244898 , 0.04897959, 0.07346939, 0.09795918,
       0.12244898, 0.14693878, 0.17142857, 0.19591837, 0.22040816,
       0.24489796, 0.26938776, 0.29387755, 0.31836735, 0.34285714,
       0.36734694, 0.39183673, 0.41632653, 0.44081633, 0.46530612,
       0.48979592, 0.51428571, 0.53877551, 0.56326531, 0.5877551 ,
       0.6122449 , 0.63673469, 0.66122449, 0.68571429, 0.71020408,
       0.73469388, 0.75918367, 0.78367347, 0.80816327, 0.83265306,
       0.85714286, 0.88163265, 0.90612245, 0.93061224, 0.95510204,
       0.97959184, 1.00408163, 1.02857143, 1.05306122, 1.07755102,
       1.10204082, 1.12653061, 1.15102041, 1.1755102 , 1.2       ])