In [1]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]
print(type(my_list))
my_list

<class 'list'>


[1, 2, 3, 4, 5]

In [5]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [6]:
my_list = [[1,2,3], [4,5,6], [7,8,9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np_matrix = np.array(my_list)
np_matrix.shape

(3, 3)

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.ones(5)*11

array([11., 11., 11., 11., 11.])

In [17]:
np.ones((3,5)) + 10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [19]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
#Identity matrx
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(1)

array([0.1042091])

In [24]:
# This is uniform distribution
np.random.rand(3,2)

array([[0.58661846, 0.2170454 ],
       [0.22404484, 0.93199403],
       [0.73442021, 0.05893323]])

In [25]:
np.random.randn(1)

array([0.58798426])

In [26]:
np.random.randn(5)

array([ 0.70977773, -0.1247648 , -2.11511789,  0.03770354, -0.55076613])

In [31]:
np.random.randint(1,100,3)

array([ 8, 88, 41])

In [33]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [35]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr = np.random.randint(0, 50,10)
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
ranarr.max()

43

In [43]:
ranarr.argmax()

7