In [2]:
import numpy as np


In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [6]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [7]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
# Slicing will point to the original array
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
slice_of_arr[:] =99
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

If you don't want to chnge your original array to be changed then do a copy of that vairable and then do the slicing operations

# Indexing of 2D Array

In [17]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[1]

array([20, 25, 30])

In [19]:
arr_2d[1][1]

25

In [20]:
arr_2d[1,1]

25

In [21]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [22]:
arr_2d[:2, :1]

array([[ 5],
       [20]])

In [23]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [26]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
arr[arr<=6]

array([1, 2, 3, 4, 5, 6])